//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.25 at 09:24:39 PM PDT 
//


package com.gomeznetworks.jaxb.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MonitorDesignator">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="MonitorClassDesignator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TXTIMEGROUP">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="monitor_id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="avail" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="avgresp" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="avgDNS" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="avgConnect" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="avgFirstByte" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="avgContent" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="avgSSL" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "monitorDesignator",
    "txtimegroup"
})
@XmlRootElement(name = "GpnResponseData")
public class GpnResponseData {

    @XmlElement(name = "MonitorDesignator", required = true)
    protected GpnResponseData.MonitorDesignator monitorDesignator;
    @XmlElement(name = "TXTIMEGROUP", required = true)
    protected GpnResponseData.TXTIMEGROUP txtimegroup;

    /**
     * Gets the value of the monitorDesignator property.
     * 
     * @return
     *     possible object is
     *     {@link GpnResponseData.MonitorDesignator }
     *     
     */
    public GpnResponseData.MonitorDesignator getMonitorDesignator() {
        return monitorDesignator;
    }

    /**
     * Sets the value of the monitorDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link GpnResponseData.MonitorDesignator }
     *     
     */
    public void setMonitorDesignator(GpnResponseData.MonitorDesignator value) {
        this.monitorDesignator = value;
    }

    /**
     * Gets the value of the txtimegroup property.
     * 
     * @return
     *     possible object is
     *     {@link GpnResponseData.TXTIMEGROUP }
     *     
     */
    public GpnResponseData.TXTIMEGROUP getTXTIMEGROUP() {
        return txtimegroup;
    }

    /**
     * Sets the value of the txtimegroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link GpnResponseData.TXTIMEGROUP }
     *     
     */
    public void setTXTIMEGROUP(GpnResponseData.TXTIMEGROUP value) {
        this.txtimegroup = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="MonitorClassDesignator" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class MonitorDesignator {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "MonitorClassDesignator")
        protected String monitorClassDesignator;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the monitorClassDesignator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonitorClassDesignator() {
            return monitorClassDesignator;
        }

        /**
         * Sets the value of the monitorClassDesignator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonitorClassDesignator(String value) {
            this.monitorClassDesignator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="monitor_id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="avail" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="avgresp" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="avgDNS" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="avgConnect" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="avgFirstByte" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="avgContent" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="avgSSL" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TXTIMEGROUP {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "monitor_id")
        protected Integer monitorId;
        @XmlAttribute(name = "avail")
        protected Float avail;
        @XmlAttribute(name = "avgresp")
        protected Float avgresp;
        @XmlAttribute(name = "avgDNS")
        protected Float avgDNS;
        @XmlAttribute(name = "avgConnect")
        protected Float avgConnect;
        @XmlAttribute(name = "avgFirstByte")
        protected Float avgFirstByte;
        @XmlAttribute(name = "avgContent")
        protected Float avgContent;
        @XmlAttribute(name = "avgSSL")
        protected Float avgSSL;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the monitorId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMonitorId() {
            return monitorId;
        }

        /**
         * Sets the value of the monitorId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMonitorId(Integer value) {
            this.monitorId = value;
        }

        /**
         * Gets the value of the avail property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getAvail() {
            return avail;
        }

        /**
         * Sets the value of the avail property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setAvail(Float value) {
            this.avail = value;
        }

        /**
         * Gets the value of the avgresp property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getAvgresp() {
            return avgresp;
        }

        /**
         * Sets the value of the avgresp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setAvgresp(Float value) {
            this.avgresp = value;
        }

        /**
         * Gets the value of the avgDNS property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getAvgDNS() {
            return avgDNS;
        }

        /**
         * Sets the value of the avgDNS property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setAvgDNS(Float value) {
            this.avgDNS = value;
        }

        /**
         * Gets the value of the avgConnect property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getAvgConnect() {
            return avgConnect;
        }

        /**
         * Sets the value of the avgConnect property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setAvgConnect(Float value) {
            this.avgConnect = value;
        }

        /**
         * Gets the value of the avgFirstByte property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getAvgFirstByte() {
            return avgFirstByte;
        }

        /**
         * Sets the value of the avgFirstByte property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setAvgFirstByte(Float value) {
            this.avgFirstByte = value;
        }

        /**
         * Gets the value of the avgContent property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getAvgContent() {
            return avgContent;
        }

        /**
         * Sets the value of the avgContent property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setAvgContent(Float value) {
            this.avgContent = value;
        }

        /**
         * Gets the value of the avgSSL property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getAvgSSL() {
            return avgSSL;
        }

        /**
         * Sets the value of the avgSSL property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setAvgSSL(Float value) {
            this.avgSSL = value;
        }

    }

}
